# Generated by Django 5.2.11 on 2026-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('content_ru', models.TextField(null=True, verbose_name='Содержание')),
                ('content_uz', models.TextField(null=True, verbose_name='Содержание')),
                ('content_en', models.TextField(null=True, verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
