# Generated by Django 5.2.11 on 2026-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='CSS-класс иконки')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('subtitle_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('button_text', models.CharField(default='Связаться с нами', max_length=100, verbose_name='Текст кнопки')),
                ('button_text_ru', models.CharField(default='Связаться с нами', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_text_uz', models.CharField(default='Связаться с нами', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_text_en', models.CharField(default='Связаться с нами', max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(default='/contacts/', max_length=300, verbose_name='Ссылка кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QualityPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='quality/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Столп качества',
                'verbose_name_plural': 'Столпы качества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='settings/', verbose_name='Логотип')),
                ('company_name', models.CharField(default='Door Company', max_length=200, verbose_name='Название компании')),
                ('company_name_ru', models.CharField(default='Door Company', max_length=200, null=True, verbose_name='Название компании')),
                ('company_name_uz', models.CharField(default='Door Company', max_length=200, null=True, verbose_name='Название компании')),
                ('company_name_en', models.CharField(default='Door Company', max_length=200, null=True, verbose_name='Название компании')),
                ('slogan', models.CharField(blank=True, max_length=300, verbose_name='Слоган')),
                ('slogan_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Слоган')),
                ('slogan_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Слоган')),
                ('slogan_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Слоган')),
                ('about_text', models.TextField(blank=True, verbose_name='О компании (краткое)')),
                ('about_text_ru', models.TextField(blank=True, null=True, verbose_name='О компании (краткое)')),
                ('about_text_uz', models.TextField(blank=True, null=True, verbose_name='О компании (краткое)')),
                ('about_text_en', models.TextField(blank=True, null=True, verbose_name='О компании (краткое)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=50, verbose_name='Телефон 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('address_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('map_embed', models.TextField(blank=True, verbose_name='Код карты (iframe)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Число')),
                ('label', models.CharField(max_length=200, verbose_name='Подпись')),
                ('label_ru', models.CharField(max_length=200, null=True, verbose_name='Подпись')),
                ('label_uz', models.CharField(max_length=200, null=True, verbose_name='Подпись')),
                ('label_en', models.CharField(max_length=200, null=True, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ['order'],
            },
        ),
    ]
