# Generated by Django 5.2.11 on 2026-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=300, verbose_name='SEO Title')),
                ('meta_title_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO Title')),
                ('meta_title_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO Title')),
                ('meta_title_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('meta_description_ru', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('meta_description_uz', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='SEO Keywords')),
                ('meta_keywords_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Keywords')),
                ('meta_keywords_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Keywords')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Keywords')),
                ('page', models.CharField(choices=[('home', 'Главная'), ('about', 'О компании'), ('catalog', 'Каталог'), ('news', 'Новости'), ('portfolio', 'Наши работы'), ('contacts', 'Контакты')], max_length=50, unique=True, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'SEO страницы',
                'verbose_name_plural': 'SEO страниц',
            },
        ),
    ]
