# Generated by Django 5.2.11 on 2026-02-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pageseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='catalog_pdf',
            field=models.FileField(blank=True, help_text='PDF-файл каталога для скачивания', upload_to='catalog/', verbose_name='PDF-каталог'),
        ),
    ]
