# Generated by Django 5.2.11 on 2026-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_catalog_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Токен бота от @BotFather', max_length=200, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата/группы для уведомлений', max_length=100, verbose_name='Telegram Chat ID'),
        ),
    ]
