# Generated by Django 5.2.11 on 2026-02-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_telegram_bot_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_accent',
            field=models.CharField(default='#8ab4e8', help_text='Иконки, подсветки', max_length=20, verbose_name='Светлый акцент'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_bg_accent',
            field=models.CharField(default='#f8fafe', max_length=20, verbose_name='Акцентный фон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_bg_light',
            field=models.CharField(default='#f5f7fa', help_text='Фон секций', max_length=20, verbose_name='Светлый фон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_danger',
            field=models.CharField(default='#e8433e', max_length=20, verbose_name='Цвет ошибки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_dark',
            field=models.CharField(default='#1a2d45', help_text='Хедер, тёмные секции', max_length=20, verbose_name='Тёмный цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_font',
            field=models.CharField(default='Inter', help_text='Название Google Fonts шрифта', max_length=100, verbose_name='Шрифт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_primary',
            field=models.CharField(default='#1b4f8a', help_text='Кнопки, ссылки, акценты', max_length=20, verbose_name='Основной цвет'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_primary_hover',
            field=models.CharField(default='#153f6e', max_length=20, verbose_name='Основной (ховер)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_success',
            field=models.CharField(default='#1b8a4b', max_length=20, verbose_name='Цвет успеха'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_text',
            field=models.CharField(default='#333333', max_length=20, verbose_name='Цвет текста'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_text_light',
            field=models.CharField(default='#777777', max_length=20, verbose_name='Вторичный текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_warning',
            field=models.CharField(default='#f5a623', help_text='Бейджи "Популярное"', max_length=20, verbose_name='Цвет предупреждения'),
        ),
    ]
