# Generated by Django 5.2.11 on 2026-04-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_theme_accent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Иконка сайта (ICO, PNG, 32x32 или 64x64)', upload_to='settings/', verbose_name='Фавиконка'),
        ),
    ]
