# Generated by Django 5.2.11 on 2026-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Картинка справа от текста «О компании» на главной', upload_to='settings/', verbose_name='Фото в блоке «О компании»'),
        ),
    ]
