# Generated by Django 5.2.11 on 2026-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_keywords_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='meta_title_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO Title'),
        ),
    ]
